#
# Run 
#
#   docker-compose up
#
version: '3'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
     - "6379:6379"
  web-app:
    build: Alpine
    image: "alpine/webapp:v1"
    container_name: web-app
    depends_on:
      - redis
    ports:
     - "8080:8080"
    environment:
      - REDIS_URL=redis://host.docker.internal:6379
    entrypoint: 
      - /sbin/sreracha
